openapi: 3.0.1
info:
  title: PassengerInfoAPI
  description: |
    This is the API definition for Passenger information backend
  version: 1.0.0
servers:
  - url: 'http://backend-service:8080/train-operations/v1'
paths:
  /passenger-count:
    get:
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Count'
components:
  schemas:
    Count:
      title: Passenger Count information.
      type: object
      properties:
        count:
          type: integer
          description: number of passengers for the given time.
        time:
          type: string
          description: Time.

