apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-api
  template:
    metadata:
      labels:
        app: product-api
    spec:
      containers:
      - name: product-api
        image: npamudika/product-api:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: product-api-service
spec:
  type: NodePort
  selector:
    app: product-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
    nodePort: 30080
