openapi: 3.0.1
info:
  title: FinancialDataAPI
  description: Financial Data API
  version: 1.0.0
servers:
  - url: http://40.81.24.192:3000/
paths:
  /:
    get:
      summary: Root
      operationId: root__get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
  /redshift/query:
    get:
      summary: Execute Query
      description: Mock endpoint to execute a query
      operationId: execute_query_redshift_query_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QueryResponse'
  /redshift/query/status/{queryId}:
    get:
      summary: Get Query Status
      description: Mock endpoint to get query execution status
      operationId: get_query_status_redshift_query_status__queryId__get
      parameters:
        - name: queryId
          in: path
          required: true
          schema:
            type: string
            title: Queryid
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QueryStatusResponse'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /redshift/insert:
    post:
      summary: Insert Data
      description: Mock endpoint to insert financial data
      operationId: insert_data_redshift_insert_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InsertData'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InsertResponse'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /redshift/data:
    get:
      summary: Get All Data
      description: Utility endpoint to view all inserted data (for testing purposes)
      operationId: get_all_data_redshift_data_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
    delete:
      summary: Clear All Data
      description: Utility endpoint to clear all data (for testing purposes)
      operationId: clear_all_data_redshift_data_delete
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
components:
  securitySchemes:
    default:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://test.com
          scopes: {}
  schemas:
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    InsertData:
      properties:
        data:
          type: object
          title: Data
      type: object
      required:
        - data
      title: InsertData
    InsertResponse:
      properties:
        success:
          type: boolean
          title: Success
        message:
          type: string
          title: Message
        record_id:
          type: string
          title: Record Id
        timestamp:
          type: string
          title: Timestamp
      type: object
      required:
        - success
        - message
        - record_id
        - timestamp
      title: InsertResponse
    QueryResponse:
      properties:
        query_id:
          type: string
          title: Query Id
        status:
          type: string
          title: Status
        message:
          type: string
          title: Message
        timestamp:
          type: string
          title: Timestamp
      type: object
      required:
        - query_id
        - status
        - message
        - timestamp
      title: QueryResponse
    QueryStatusResponse:
      properties:
        query_id:
          type: string
          title: Query Id
        status:
          type: string
          title: Status
        progress:
          type: integer
          title: Progress
        result:
          anyOf:
            - type: object
            - type: string
          title: Result
        timestamp:
          type: string
          title: Timestamp
      type: object
      required:
        - query_id
        - status
        - progress
        - timestamp
      title: QueryStatusResponse
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
              - type: string
              - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
        - loc
        - msg
        - type
      title: ValidationError
x-wso2-api-key-header: ApiKey
x-wso2-auth-header: Authorization
x-wso2-cors:
  corsConfigurationEnabled: false
  accessControlAllowOrigins:
    - '*'
  accessControlAllowCredentials: false
  accessControlAllowHeaders:
    - authorization
    - Access-Control-Allow-Origin
    - Content-Type
    - SOAPAction
    - apikey
    - Internal-Key
  accessControlAllowMethods:
    - GET
    - PUT
    - POST
    - DELETE
    - PATCH
    - OPTIONS
x-wso2-production-endpoints:
  urls:
    - http://40.81.24.192:3000/
  type: http
x-wso2-sandbox-endpoints:
  urls:
    - http://40.81.24.192:3000/
  type: http
x-wso2-basePath: /financialdataapi/1.0.0
x-wso2-transports:
  - http
  - https
x-wso2-application-security:
  security-types:
    - oauth2
  optional: false
x-wso2-response-cache:
  enabled: false
  cacheTimeoutInSeconds: 300
security:
  - default: []
