[server]
hostname = "localhost"
hot_deployment = false
# offset  = 10

[user_store]
type = "read_only_ldap"

[keystore.primary]
file_name = "repository/resources/security/wso2carbon.jks"
password = "wso2carbon"
alias = "wso2carbon"
key_password = "wso2carbon"

[truststore]
file_name = "repository/resources/security/client-truststore.jks"
password = "wso2carbon"
alias = "symmetric.key.value"
algorithm = "AES"

[[service_catalog]]
apim_host = "https://api-manager:9443"
enable = true
username = "jill@railco.com"
password = "user123"
