[server]
hostname = "localhost"
server_role = "default"
offset = 3

[user_store]
type = "database_unique_id"

[super_admin]
username = "admin"
password = "admin"
create_admin_account = true

[database.shared_db]
type = "mysql"
url = "jdbc:mysql://127.0.0.1:3316/shared_db?autoReconnect=true&amp;allowPublicKeyRetrieval=true&amp;useSSL=false"
username = "sharedadmin"
password = "sharedadmin"
driver = "com.mysql.cj.jdbc.Driver"

[keystore.tls]
file_name =  "wso2carbon.jks"
type =  "JKS"
password =  "wso2carbon"
alias =  "wso2carbon"
key_password =  "wso2carbon"

[truststore]
file_name = "client-truststore.jks"
type = "JKS"
password = "wso2carbon"

# key manager implementation
[apim.key_manager]
service_url = "https://localhost:9444/services/"
username= "$ref{super_admin.username}"
password= "$ref{super_admin.password}"

# Event Hub configurations
[apim.event_hub]
enable = true
username = "$ref{super_admin.username}"
password = "$ref{super_admin.password}"
service_url = "https://localhost:9444/services/"
event_listening_endpoints = ["tcp://localhost:5673"]

[apim.sync_runtime_artifacts.gateway]
gateway_labels =["Default"]

[apim.throttling]
throttle_decision_endpoints = ["tcp://localhost:5674"]

[[apim.throttling.url_group]]
traffic_manager_urls = ["tcp://localhost:9613"]
traffic_manager_auth_urls = ["ssl://localhost:9713"]

[apim.analytics]
enable = false
config_endpoint = "https://localhost:8080/auth/v1"
auth_token = ""

# Caches
[apim.cache.gateway_token]
enable = true
expiry_time = 15

[apim.cache.resource]
enable = true

[apim.cache.jwt_claim]
enable = true
expiry_time = 900

[apim.oauth_config]
remove_outbound_auth_header = true
auth_header = "Authorization"

[apim.cors]
allow_origins = "*"
allow_methods = ["GET","PUT","POST","DELETE","PATCH","OPTIONS"]
allow_headers = ["authorization","Access-Control-Allow-Origin","Content-Type","SOAPAction","apikey","Internal-Key"]
allow_credentials = false
