# Auto Generated Dockerfile

FROM ballerina/ballerina-runtime:0.990.2
LABEL maintainer="dev@ballerina.io"

COPY k8s_demo_service.balx /home/ballerina 

EXPOSE  9090
CMD ballerina run  k8s_demo_service.balx
