# Auto Generated Dockerfile

FROM ballerina/ballerina-runtime:0.990.2
LABEL maintainer="dev@ballerina.io"

COPY helloKubernetesService.balx /home/ballerina 

EXPOSE  9090
CMD ballerina run  helloKubernetesService.balx
