import os

CHOREO = "choreo"
APIM = "apim"

# streaming stage constants
START_STREAM = "START_STREAM"
FIND_LLM_RESPONSE = "FIND_LLM_RESPONSE"
SEND_LLM_RESPONSE = "SEND_LLM_RESPONSE"
END_LLM_RESPONSE = "END_LLM_RESPONSE"
FIND_API = "FIND_API"
SEND_API = "SEND_API"
BUFFER_API = "BUFFER_API"
FINISH_STREAM = "FINISH_STREAM"

ZILLIZ_CLOUD_URI = os.getenv('ZILLIZ_CLOUD_URI', "")
ZILLIZ_CLOUD_API_KEY = os.getenv('ZILLIZ_CLOUD_API_KEY', "")
AZURE_ENDPOINT = os.getenv('AZURE_ENDPOINT')
AZURE_API_KEY = os.getenv("OPENAI_API_KEY")
AZURE_EMBEDDING_DEPLOYMENT = os.getenv('AZURE_EMBEDDING_DEPLOYMENT', "OpenAPIEmbeddings")
AZURE_CHAT_DEPLOYMENT = os.getenv('AZURE_CHAT_DEPLOYMENT', "APIM-Deployment")
AZURE_CHAT_VERSION = os.getenv('AZURE_CHAT_VERSION', "2025-04-01-preview")
SOURCE_PLATFORM = os.getenv('SOURCE_PLATFORM')
PROXY_URL = os.getenv('PROXY_URL')
PROXY_HEALTH_CHECK_CACHE_TTL = int(os.getenv('PROXY_HEALTH_CHECK_CACHE_TTL', '900'))
TOKEN_CACHE_SIZE = int(os.getenv("TOKEN_CACHE_SIZE", "50"))
TOKEN_CACHE_TTL = int(os.getenv("TOKEN_CACHE_TTL", "870"))

# azure openai proxy related env variables
USE_PROXY = os.getenv("USE_PROXY", "false").lower() == "true"
CLIENT_ID = os.getenv("CLIENT_ID")
CLIENT_SECRET = os.getenv("CLIENT_SECRET") 
TOKEN_ENDPOINT_URL = os.getenv("TOKEN_ENDPOINT_URL")
AZURE_CHAT_PROXY_ENDPOINT = os.getenv("AZURE_CHAT_PROXY_ENDPOINT")
AZURE_EMBEDDING_PROXY_ENDPOINT = os.getenv('AZURE_EMBEDDING_PROXY_ENDPOINT')

OUTPUT_FIELDS = ['id', 'metadata', 'api_type', 'api_name', 'page_content', 'org_id']
